### ISSUE TITLE
Error running the plugin

### ISSUE THREAD

**Issue by pcav** [faunalia/processinglwgeomprovider#1]
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/sextante/core/GeoAlgorithm.py", line 147, in
execute
    self.processAlgorithm(progress)
  File "/home/paolo/.qgis2/python/plugins/sextantelwgeomprovider/LwgeomAlgorithm.py",
line 78, in processAlgorithm
    liblwgeom = self.getLwgeomLibrary()
  File "/home/paolo/.qgis2/python/plugins/sextantelwgeomprovider/LwgeomAlgorithm.py",
line 68, in getLwgeomLibrary
    lib.lwgeom_set_handlers(None, None, None, errorreporter, None)
  File "/usr/lib/python2.7/ctypes/**init**.py", line 378, in **getattr**
    func = self.**getitem**(name)
  File "/usr/lib/python2.7/ctypes/**init**.py", line 383, in **getitem**
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/bin/qgis.bin: undefined symbol: lwgeom_set_handlers

**Comment by luipir** [comment]
what's the postgis version? did you compiled liblwgeom? what is it's version?

**Comment by luipir** [comment]
lwgeom_set_handlers is not present in postgis-2.0.2 but only in trunk

http://postgis.net/docs/doxygen/2.2/da/de7/liblwgeom_8h_aab8f482cd0b8801434b4dd039342b169.html

this was introduced by Giuseppe Sucameli to allow liblwgeom as standalone library as stated in:
https://github.com/postgis/postgis/pull/4

**Comment by pcav** [comment]
liblwgeom-2.0.3, from deb sid

**Comment by pcav** [comment]
lwgeom 2.1 (to be released) is necessary

**Comment by luipir** [comment]
As stated here [1] at the moment the plugin can be installed only with trunk version of the postgis/liblwgeom

there's NO plan to apply patch [1] to 2.0 release but in 2.1 (there is RC available). Plugins will be installable as soon as 2.1 will be available.

[1] http://trac.osgeo.org/postgis/ticket/2089
