### ISSUE TITLE
python error choosing library path on OsX

### ISSUE THREAD

**Issue by gioman** [faunalia/processinglwgeomprovider#7]
Traceback (most recent call last):
  File "/Users/zealmeida/.qgis2/python/plugins/processing/gui/ConfigDialog.py", line 186, in createEditor
    value = self.convertValue(index.model().data(index, Qt.EditRole))
  File "/Users/zealmeida/.qgis2/python/plugins/processing/gui/ConfigDialog.py", line 235, in convertValue
    return int(value)
TypeError: int() argument must be a string or a number, not ‘QPyNullVariant'

**Comment by luipir** [comment]
I can't check on OsX, but why do you think it's a plugin problem? seems related with the configuration interface of Processing

the only parameter (asked by processing) is the LWGEOM_PATH_SETTING and is set as all provideres => probably a problem in Processing
